GET https://cowork-api-server-prac.herokuapp.com/api/members

###

POST https://cowork-api-server-prac.herokuapp.com/api/members 
Content-Type: application/json

{
    "name": "William",
    "team": "engineering",
    "position": "Android Developer",
    "emailAddress": "zake@gamil.com",
    "phoneNumber": "010-1221-3443",
    "admissionDate": "2022/06/17",
    "birthday":"1995/04/03",
    "profileImage": "profile11.png"
}

###
PUT https://cowork-api-server-prac.herokuapp.com/api/members/1
Content-Type: application/json

{
    "position": "Android Developer"
}

###
DELETE https://cowork-api-server-prac.herokuapp.com/api/members/2